spring:
    data:
        mongodb:
            database: vyiradb
            port: 27017
            host: vyirasuite-mongodb
    application:
        name: quiz-server

server:
    port: 8090

api:
    version: v1

# Comment out below values to run in local
########## Start Comment
eureka:
    instance:
        hostname: vyirasuite-discovery-server
    client:
        service-url:
            defaultZone: http://vyirasuite-discovery-server:8761/eureka/

######### End Comment
