## Spring Boot properties
spring:
    data:
        mongodb:
            database: vyiradb
            port: 27017
            host: vyirasuite-mongodb
            auto-index-creation: true
    application:
        name: quiz-server

logging:
    level:
        root: debug
    file:
        name: logs/${spring.application.name}-log.log

server:
    port: 8090

## Application Properties
api:
    version: v1

# Comment out below values to run in local
########## Start Comment
eureka:
    instance:
        hostname: vyirasuite-discovery-server
    client:
        service-url:
            defaultZone: http://vyirasuite-discovery-server:8761/eureka/

######### End Comment
