#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF
## Spring Properties
server:
    port: 8761

eureka:
    client:
        register-with-eureka: false
        fetch-registry: false

logging:
    level:
        root: INFO
    file:
        name: logs/${spring.application.name}-log.log


## Application properties
api:
    version: v1
spring:
    application:
        name: discovery-server