spring:
    data:
        mongodb:
            database: vyiradb
            port: 27017
            host: vyirasuite-mongodb
    application:
        name: recruits
server:
    port: 8091

api:
    version: v1

eureka:
    instance:
        hostname: vyirasuite-discovery-server
    client:
        service-url:
            defaultZone: http://vyirasuite-discovery-server:8761/eureka/
